// =============================================================================
//  CHINA WOK — Unsplash placeholder image fetcher
// =============================================================================
//  Reads the search queries in data/images.js, asks the Unsplash API for one
//  warm, landscape photo per slot, and writes the results to
//  data/images.generated.js (which the site reads at runtime).
//
//  USAGE:
//    1. Get a free Unsplash access key: https://unsplash.com/developers
//    2. Copy .env.example to .env and paste your key, OR run inline:
//         UNSPLASH_ACCESS_KEY=xxxx npm run fetch:images
//    3. Run:  npm run fetch:images
//
//  Requires Node 18+ (uses the built-in fetch). No npm packages needed.
// =============================================================================

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { IMAGES } from "../data/images.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const OUT_FILE = resolve(ROOT, "data/images.generated.js");

const API = "https://api.unsplash.com";
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

// Pixel widths requested per slot type (Unsplash resizes on the fly).
const widthFor = (slot) => (slot === "hero" ? 2000 : slot === "about" ? 1200 : 1000);

/* ---------- minimal .env loader (no dependency) ---------- */
function loadDotEnv() {
  const envPath = resolve(ROOT, ".env");
  if (!existsSync(envPath)) return;
  for (const line of readFileSync(envPath, "utf8").split("\n")) {
    const m = line.match(/^\s*([\w.-]+)\s*=\s*(.*)\s*$/);
    if (!m) continue;
    const key = m[1];
    let val = m[2].trim().replace(/^["']|["']$/g, "");
    if (!(key in process.env)) process.env[key] = val;
  }
}

/* ---------- Unsplash calls ---------- */
async function searchOne(query, key) {
  const url =
    `${API}/search/photos?per_page=1&orientation=landscape&content_filter=high` +
    `&order_by=relevant&query=${encodeURIComponent(query)}`;
  const res = await fetch(url, { headers: { Authorization: `Client-ID ${key}`, "Accept-Version": "v1" } });

  if (res.status === 401) throw new Error("Unauthorized — check UNSPLASH_ACCESS_KEY.");
  if (res.status === 403) throw new Error("Rate limited by Unsplash (free tier = 50 requests/hour). Try again later.");
  if (!res.ok) throw new Error(`Unsplash error ${res.status}`);

  const data = await res.json();
  return data.results && data.results[0] ? data.results[0] : null;
}

// Per Unsplash API guidelines, trigger the download endpoint when a photo is used.
async function triggerDownload(photo, key) {
  try {
    const loc = photo.links && photo.links.download_location;
    if (loc) await fetch(loc, { headers: { Authorization: `Client-ID ${key}` } });
  } catch {
    /* non-fatal */
  }
}

/* ---------- main ---------- */
async function main() {
  loadDotEnv();
  const key = process.env.UNSPLASH_ACCESS_KEY;
  if (!key || key === "your-unsplash-access-key-here") {
    console.error("\n✗ No Unsplash key found.\n  1) Get one free at https://unsplash.com/developers" +
      "\n  2) Copy .env.example to .env and paste it in (or prefix the command with UNSPLASH_ACCESS_KEY=...).\n");
    process.exit(1);
  }

  const slots = IMAGES.slots || {};
  const todo = Object.entries(slots).filter(([, cfg]) => !cfg.src && cfg.query);
  if (todo.length === 0) {
    console.log("Nothing to fetch — every slot already has a `src` set. ✓");
    return;
  }

  console.log(`\nFetching ${todo.length} placeholder image(s) from Unsplash…\n`);
  const generated = {};
  let ok = 0;

  for (const [slot, cfg] of todo) {
    try {
      const photo = await searchOne(cfg.query, key);
      if (!photo) {
        console.warn(`  ⚠ ${slot}: no results for "${cfg.query}" — leaving placeholder.`);
        continue;
      }
      await triggerDownload(photo, key);

      const w = widthFor(slot);
      const url = `${photo.urls.raw}&q=80&fm=jpg&fit=crop&w=${w}`;
      generated[slot] = {
        url,
        alt: cfg.alt || photo.alt_description || "",
        credit: {
          name: photo.user.name,
          profileUrl: photo.user.links.html,
          photoUrl: photo.links.html,
        },
      };
      ok++;
      console.log(`  ✓ ${slot}  —  ${photo.user.name}`);
      await sleep(250); // be polite to the API
    } catch (err) {
      console.error(`  ✗ ${slot}: ${err.message}`);
      // Stop early on auth/rate-limit errors; they won't fix themselves mid-run.
      if (/Unauthorized|Rate limited/.test(err.message)) break;
    }
  }

  const banner =
    "// =============================================================================\n" +
    "//  AUTO-GENERATED by scripts/fetch-images.mjs — do not edit by hand.\n" +
    `//  Generated: ${new Date().toISOString()}\n` +
    "// =============================================================================\n\n";
  writeFileSync(OUT_FILE, `${banner}export const GENERATED = ${JSON.stringify(generated, null, 2)};\n`);

  console.log(`\nDone. ${ok}/${todo.length} image(s) saved to data/images.generated.js`);
  if (ok > 0) console.log("Reload the site to see them. Photo credits appear automatically in the footer.\n");
}

main().catch((err) => {
  console.error("\nUnexpected error:", err);
  process.exit(1);
});
